import { betterAuth } from "better-auth";
import { drizzleAdapter } from "@better-auth/drizzle-adapter/relations-v2";
import { multiSession, organization } from "better-auth/plugins";
import { db } from "@/db";

export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "pg",
    // Tables are exported as users/sessions/accounts/verifications (db/schema).
    usePlural: true,
  }),
  plugins: [
    multiSession(),
    // Tables are plural: organizations/members/invitations/teams/teamMembers
    // (db/schema); sessions.activeOrganizationId/activeTeamId are defined in
    // db/schema/sessions.ts.
    organization({
      teams: {
        enabled: true,
        // maximumTeams: 10,
        // maximumMembersPerTeam: 50,
        // allowRemovingAllTeams: false, // false = last team cannot be removed
        // defaultTeam: { enabled: true }, // auto-create a default team per org
      },
    }),
  ],
  advanced: {
    database: {
      // Ids are uuid columns generated by Postgres.
      generateId: "uuid",
      joins: true,
    },
  },
});
