import { betterAuth } from "better-auth";
import { drizzleAdapter } from "@better-auth/drizzle-adapter/relations-v2";
import { db } from "@/db";

export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "pg",
    // Tables are exported as users/sessions/accounts/verifications (db/schema).
    usePlural: true,
  }),

  advanced: {
    database: {
      // Ids are uuid columns generated by Postgres.
      generateId: "uuid",
      joins: true,
    },
  },
});
